name: Terraform Plan
on:
  pull_request:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: terraform init
      - run: terraform plan
