name: Terraform Security Scan
on: pull_request
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Checkov Scan
        run: checkov -d .  
